version: '3'
services:

  backend:
    build:
      context: ./backend
    restart: 'unless-stopped'
    privileged: true
    volumes:
      - ./backend/src:/app/src
    environment:
      - CONN_STR=mongodb://user:pass@mongodb
      - TZ=America/Toronto
    ports:
      - "8000:8000"
    depends_on:
      - mongodb

  frontend:
    build: 
      context: ./frontend
    privileged: true
    network_mode: "host"
    volumes:
      - ./frontend/src:/app/src
    environment:
      - TZ=America/Toronto

  mongodb:
    image: mongo:latest
    environment:
      - MONGODB_INITDB_ROOT_USERNAME=user
      - MONGODB_INITDB_ROOT_PASSWORD=pass
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8082:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: user
      ME_CONFIG_MONGODB_ADMINPASSWORD: pass
      ME_CONFIG_MONGODB_URL: mongodb://user:pass@mongodb:27017/

volumes:
  mongodb-data:




